### ISSUE TITLE
Support node managers (nodenv, mise, etc.)

### ISSUE THREAD

**Issue by IlyaSemenov** [toplenboren/simple-git-hooks#102]
When using certain node version managers, there is sometimes no `npx` executable in path, and commit hooks fail when executed from a GUI git client:

```
.git/hooks/pre-commit: line 2: npx: command not found
```

husky works around that case by executing `~/.huskyrc` prior to commit hook: https://github.com/typicode/husky/issues/369

For instance, for [mise](https://github.com/jdx/mise) it would contain:

```sh
export PATH="$HOME/.local/share/mise/shims:$PATH"
```

Can we have a similar option in simple-git-hooks?

**Comment by toplenboren** [comment]
Hi, nice suggestion. Feel free to send pull request to this repo 🚀

**Comment by toplenboren** [comment]
Should be live in `2.10.0`. Thanks @IlyaSemenov for the issue and the fix!
