### ISSUE TITLE
Postinstall script is not being executed

### ISSUE THREAD

**Issue by CaptainLiao** [toplenboren/simple-git-hooks#106]
Thanks for your working. I'm love it.

But when I use yarn to install simple-git-hooks, the postinstall script is not being executed. It's yarn's bug that not be fixed. [see 5476](https://github.com/yarnpkg/yarn/issues/5476).

Would you please offer install script replace postinstall? Like [pre-commit](https://github.com/observing/pre-commit/blob/master/package.json#L10).

**Comment by toplenboren** [comment]
Hi! Thanks for the issue

You can run `npx simple-git-hooks` and the hooks will be installed manually

--

In future versions we can add `install: ./postinstall.js` in `package.json`, will it fix your issue?

**Comment by CaptainLiao** [comment]
Yeah,`npx simple-git-hooks` address the issue.

Awaiting the new version~
