### ISSUE TITLE
Some question about `pre-push: cd ../../`  in README.md

### ISSUE THREAD

**Issue by lisonge** [toplenboren/simple-git-hooks#109]
Thank you for creating this very useful tool

But I have some questions about the documentation

https://github.com/toplenboren/simple-git-hooks/blob/b859665621d26969c8fbb8119d94b43fe4c03ee3/README.md?plain=1#L78

I've seen the all examples of `pre-push` has startsWith `cd ../../`

but it will case some bug when work with <https://github.com/ad-m/github-push-action>

![image](https://github.com/toplenboren/simple-git-hooks/assets/38517192/740b4960-e552-442a-b0b0-40888eaa19ab)

What is the use of  `cd ../../` ?

I think this will make beginners mistakenly think that the execution path of `pre-push` is inconsistent with other hooks

**Comment by lisonge** [comment]
error link <https://github.com/gkd-kit/subscription-template/actions/runs/8692458080/job/23837135632>

**Comment by toplenboren** [comment]
Thanks for your kind words!

True, it is strange that `pre-push` starts with `cd ../..` in `README`.. I will investigate :-) 

By the way, what is the usecase of running `simple-git-hooks` in `CI` ? You can skip execution of git hooks in CI using environment variable `SKIP_SIMPLE_GIT_HOOKS=1`

**Comment by lisonge** [comment]
> By the way, what is the usecase of running simple-git-hooks in CI ? You can skip execution of git hooks in CI using environment variable SKIP_SIMPLE_GIT_HOOKS=1

Some users choose to commit the code on the GitHub web editor. These commits formats are chaotic, so automatic format and recommit are needed

If their commits is complied with the format specifications, it will not trigger the automatic formatting

**Comment by toplenboren** [comment]
Just checked that out. 

I used `cd mainly because my project was using yarn monorepo at the time and I needed to change directories prior to executing npm script`

Removed `cd ..` part from `README.md`
