### ISSUE TITLE
Other hook support

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-git-hooks#14]
Maybe I made a mistake by suggesting only `pre-commit` hook support. We can add other hook support, but it will require the project to change the name (`simple-hooks`?).

We can have the same one-line config for `pre-commit`:

```json
  "simple-hooks": "npx lint-staged"
```

And object for custom hooks:

```json
  "simple-hooks": {
    "pre-push": "npx x"
  }
```

**Comment by ai** [comment]
But it is still an open question, should we support other hooks.

**Comment by just-boris** [comment]
If you are wondering about use-case, I am onboard after `commit-msg` support (we have auto-generated changelogs)

**Comment by toplenboren** [comment]
Yep, the idea is great, if we do it right then core features would stay :)
