### ISSUE TITLE
Package’s name

### ISSUE THREAD

**Issue by valtlai** [toplenboren/simple-git-hooks#22]
Now that the package is being renamed (#21), should we consider a shorter name? I found that the following are unused in npm:
* hook-setter
* set-hook(s)
* add-hook(s)
* install-hook(s)
* hookful
* hookize
* hookish

For example, *set-hooks* would work well as a command: `npx set-hooks`. On the other hand, it would’t be so good property name in `package.json`.

**Comment by toplenboren** [comment]
Hey! Thanks for the submission

The package is being renamed mainly because we plan to change core functionality — add an ability to set any `.git` hook, instead of only `pre-commit`. See #14 for details

I like the idea of the shorter name, `hookful` or `hookize`, maybe `hookie` :)

I'm afraid it does not sound similar to the `simple-pre-commit` and it may look like the package is about `React` hooks, so I dont know

What do you think?

**Comment by valtlai** [comment]
I’m aware of #14, but I think it’s a good opportunity to consider a shorter name when the name is changing anyway.

The name *simple-git-hooks* is very self-explanatory, like the current one, which is nice. The simplicity is what can distinguish the package from similar ones.

I would like *hookie* too, but unfortunately it’s already reserved. So are many others, such as *hookly*, *hooker*, *hooking*, *hooked* and *hookify*. But *hookish* is not, so I added it on the list.

Yeah, maybe these are too vague, since *hook* may mean many things in programming. I’m not sure if they are associated with React too much.

Maybe we can invent a short name containing both *git* and *hook*. But if the simplicity is an important point, maybe *simple-git-hooks* is the best name and the shortness isn’t so relevant.

**Comment by valtlai** [comment]
> Maybe we can invent a short name containing both *git* and *hook*.

What about *git-hookie*?

It’s more explicit and still short. The diminutive suffix *-ie*, referring to littleness, and the simplicity have something in common, in my opinion.

**Comment by toplenboren** [comment]
Yep, I like the `git-hookie` but still like the current name, as its really self-explanatory

Gonna think about it, thanks!

**Comment by toplenboren** [comment]
I like the original name and the renaming was done by the time we had this issue opened, so I decided to leave the name as it is.
