### ISSUE TITLE
Sharable configuration support

### ISSUE THREAD

**Issue by JounQin** [toplenboren/simple-git-hooks#24]
I'm still using husky@4 because we share husky config in all of my projects:

```js
// .huskyrc.js
modue.exports = require('@1stg/husky-confog')
```

**Comment by toplenboren** [comment]
It seems like if we add an ability to parse configuration from `simple-git-hooks.js or simple-pre-commit.js` then sharable config would work

I think we should start working on this feature after we release the #21

**Comment by JounQin** [comment]
@toplenboren Are you working on this? Or I can raise a PR.

**Comment by toplenboren** [comment]
@JounQin no, currently I'm not working on it.  
Please feel free to raise a PR

**Comment by JounQin** [comment]
@toplenboren Please check #37
