### ISSUE TITLE
Add “Who uses simple-git-hooks” to docs

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-git-hooks#29]
Big names are a good way to convince users in our hype-driven community. Here are a few names, which we can add to docs:

* Autoprefixer
* PostCSS
* Browserslist
* Nano ID
* [full list](https://github.com/toplenboren/simple-git-hooks/network/dependents)

A few examples of the section in my projects:
* https://github.com/ai/size-limit/#who-uses-size-limit
* https://github.com/browserslist/browserslist#browserslist-

**Comment by toplenboren** [comment]
Thank you!
