### ISSUE TITLE
Use dependencies size in size table

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-git-hooks#36]
According to [husky 4→5 post](https://dev.to/typicode/what-s-new-in-husky-5-32g5) husky 4 uses 1 MB of the size.

But in your table, it is only 50 KB. Seems like you are not using dependencies in size calculation. It will increase the size of husky 4 and pre-commit a lot. And it will be pretty fair since dependencies size is the main reason to avoid dependencies for small projects.

**Comment by toplenboren** [comment]
Thanks for the issue!

Updated the docs, by adding the new column — size with dependencies. 

`Husky 4` was increased to 1mb, 
`Pre-commit` stayed on ~80kb, I measured it on local node-modules, since `npm` does not provide size for `pre-commit`

**Comment by ai** [comment]
`pre-commit` has 3 dependencies. The size with deps should be bigger than without deps.

I think the best way to get the size is to create an empty project, add only 1 dependencies and then check `node_modules` size.

```sh
mkdir test
yarn add pre-commit
du -hs node_modules
856K	node_modules
```

**Comment by toplenboren** [comment]
Double cheked it, you were right, thanks!
