### ISSUE TITLE
removed hooks are not deleted

### ISSUE THREAD

**Issue by JounQin** [toplenboren/simple-git-hooks#39]
<del>I see `commit-msg` hook is supported, but I tried like following and failed:</del>

```js
module.exports = {
  'pre-commit': 'npx lint-staged',
  'commit-msg': 'npx commitlint -e', // it will work
}
```

**Comment by JounQin** [comment]
It seems that `npx simple-git-hooks` will not unset removed hooks...

I added `prepare-commit-msg` before and remove it then.

I can only remove `.git/hooks/prepare-commit-msg` manually as a workaround for now.

**Comment by toplenboren** [comment]
Thanks for the issue!

Yep, npx simple-git-hooks just gets the config, then adds / updates hooks. It does not handle the situation when you remove one hook and add another in config. 

We can only remove all hooks when we uninstall the project

Adding this functionality is a good idea.

**Comment by JounQin** [comment]
Shall we call `removeHooks()` before https://github.com/toplenboren/simple-git-hooks/blob/master/cli.js#L10? I'll raise a PR for it.
