### ISSUE TITLE
Git hooks are not running after migrating from husky

### ISSUE THREAD

**Issue by neveenatik** [toplenboren/simple-git-hooks#44]
It is not a bug but rather a documentation suggestion. We recently migrated from husky to simple-git-hooks which is nice and easy to setup so thank you for that. However we noticed that the hooks aren't running anymore.
After a deep investigation I noticed that the source of the issue was git configurations.
`core.hooksPath` was set to `.husky` and it needed to be `$GIT_DIR/hooks`
This would be solved by changing the `core.hooksPath` or deleting project and recloning it.
Since the library relies on default git configuration I think it would make sense to be mentioned in the documentation.
I would also like to know if you know a better way to solve this issue.

Thanks again

**Comment by toplenboren** [comment]
Hey, thank you for the issue! Didn't know that.

I'm going to add this to the documentation, today or tomorrow

**Comment by toplenboren** [comment]
I updated the docs, by adding a FAQ section. Thank you!

https://github.com/toplenboren/simple-git-hooks/blob/master/README.md#common-issues
