### ISSUE TITLE
Do not remove git hooks

### ISSUE THREAD

**Issue by nseni** [toplenboren/simple-git-hooks#49]
Hi. I use some custom commit-msg and prepare-commit-msg git hooks that grab data from a Jira system. And I use "simple-git-hooks" to run "lint-staged" on "pre-commit". The latest release of "simple-git-hooks" started removing "not-used git hooks" which breaks manually created git hooks. Could you please revert this change, or make it configurable maybe?

**Comment by toplenboren** [comment]
Hey, thanks for the issue! Didn't think of this while releasing new version. Gonna make it configurable and ask if user wants to remove git hooks unused by package

You can use previous version - 2.2.0, it doesn't remove any git hooks

**Comment by JounQin** [comment]
Sorry, but out of curiosity, why these hooks cannot be configured by this package at the same time?

**Comment by nseni** [comment]
@JounQin These hooks are my personal and shouldn't be part of committed configs

**Comment by JounQin** [comment]
@toplenboren I'd like to raise a PR for it.

How about an option named `removeUnusedHooks: boolean | string []`, `true` by default, when `false`, do nothing, when `string[]`, remove unsed hooks except mentioned list.

The question is, should we move all hooks into a nested property like `husky@4` or just flatten all hooks and options.
