### ISSUE TITLE
npm version and git repository is not synchronized

### ISSUE THREAD

**Issue by JounQin** [toplenboren/simple-git-hooks#50]
It's a bit confusing.

And there is no CHANGELOG.

**Comment by ThisWillDoIt** [comment]
There is no changelog.md, but the release seciton of github is updated :-)
https://github.com/toplenboren/simple-git-hooks/releases

**Comment by JounQin** [comment]
Maybe something like https://github.com/mdx-js/mdx/blob/main/changelog.md would be helpful.

**Comment by JounQin** [comment]
cc @toplenboren

**Comment by toplenboren** [comment]
Fixed the version in package.json and added the changelog.md :) thanks for the idea and the issue

> Maybe something like https://github.com/mdx-js/mdx/blob/main/changelog.md would be helpful.
