### ISSUE TITLE
docs: Is "*" in readme means something?

### ISSUE THREAD

**Issue by vltansky** [toplenboren/simple-git-hooks#51]
Hey, just noticed that there is an asterisk after "Lightweight", I thought that it's a reference but didn't find anything relevant. Is it meant to be there or just a mistake?
![image](https://user-images.githubusercontent.com/5851280/114026470-f34ad100-987e-11eb-9c7b-575e7e6eafc4.png)

**Comment by toplenboren** [comment]
It's here more for just styling. It refers to the comparison table below, but it's obvious either way

**Comment by vltansky** [comment]
I'd suggest to remove it, made me think that comparison isn't that straightforward and there is "small letters" somewhere ;)

**Comment by toplenboren** [comment]
Fixed, Thanks!
