### ISSUE TITLE
Doesn't work with git worktrees

### ISSUE THREAD

**Issue by niklaas** [toplenboren/simple-git-hooks#58]
I get the following errror

```
ENOENT: no such file or directory, open '/Users/niklaas/git/abc/def/.git/worktrees/<name of worktree>/hooks/pre-commit'
```

when running `npx simple-pre-commit` inside a [git worktree](https://git-scm.com/docs/git-worktree).

**Comment by toplenboren** [comment]
Yep, I think we do not support any custom git configurations right now. Thanks for the issue
