### ISSUE TITLE
npm ci --production fails on simple-git-hooks

### ISSUE THREAD

**Issue by ThreePalmTrees** [toplenboren/simple-git-hooks#59]
> node: 'v14.15.4', npm: '7.19.0'

Hi

When I run `npm ci` the `"prepare"` script (which is running `npx simple-git-hooks`) runs without issues

![npm ci](https://user-images.githubusercontent.com/37015049/128244707-04355c31-b614-48c2-a08c-ac6b7f21b41e.png)

But when I run `npm ci --production` I'm prompted with this

![npm ci --proudction](https://user-images.githubusercontent.com/37015049/128218373-5412fc56-121b-4b70-848e-6234f67a15ab.png)

Which fails when I type `y`

<img src="https://user-images.githubusercontent.com/37015049/128218888-c2a153d7-aec6-46f1-a7f7-e202108a296b.png" width="500" />

Running `npx simple-git-hooks` doesn't throw any errors

![Screenshot 2021-08-04 at 18 32 10](https://user-images.githubusercontent.com/37015049/128219477-5bc6ba84-6413-47ce-abd6-336455b66a46.png)

My package.json looks something like this
```json
"dependencies": {...},
"scripts": {
  ...
  "prepare": "npx simple-git-hooks"
},
"simple-git-hooks": {
  "pre-commit": "npx lint-staged && npm run test",
  "pre-push": "npx tsc --project ./tsconfig.json --noEmit"
},
```

I'm curious if this is an issue with my setup, or with simple-git-hooks

Thanks.

**Comment by toplenboren** [comment]
Hi, thank you for the issue


**About the prompt...**
Usually you would put `simple-git-hooks` under devDependencies and use them only in dev mode on a local machine. When you run `npm ci --production` npm doesnt install dev dependencies, thus why the prompt

**About the second question...**
I think maybe the description for the `npx simple git hooks` is not clear in the docs :( The command just sets user-defined hooks under the `.git/hooks` directory. It does not run hooks or do anything else. 

It seems for me like you want `simple-git-hooks` to run hooks on ci, but this package wasn't designed for this

I would've simply hardcoded needed hooks commands inside of `npm ci` command and used `simple-git-hooks` only on local dev enviroment
