### ISSUE TITLE
Allow array of hooks

### ISSUE THREAD

**Issue by Dunky13** [toplenboren/simple-git-hooks#67]
It would be nice to have the ability to define multiple hook commands.
Probabily would need a modifaction in the [_setHook](https://github.com/toplenboren/simple-git-hooks/blob/99afedcf1e9782e9751c124665461bedff8232bd/simple-git-hooks.js#L162) function. 
To append multiple shell commands with a `;` or `&&`.

This would allow for something like:
```js
.simple-git-hooks.js
module.exports = {
   ...require('shared-package-with-base-hooks'),
   'pre-commit': ['echo "1"', 'echo "2"', 'echo "3"']
}

shared-package-with-base-hooks -> entry.js
module.export = {
   'pre-commit': 'echo "base package"',
}
```

Expected functionality:
On `pre-commit` print:
```
base package
1
2
3
```

Hope this makes sense.

Ps, the `...require(....)` would basically evaluate to:
```js
module.exports = {
   'pre-commit': 'echo "base package"',
   'pre-commit': ['echo "1"', 'echo "2"', 'echo "3"']
}
```
So not sure if that's possible or not. As the second `pre-commit` probably overwrites the initial one? But there could be alternatives probably? One example alternative would be this [StackOverflow](https://stackoverflow.com/questions/54362577/merge-duplicate-keys-in-simple-object)

**Comment by toplenboren** [comment]
Closing the issue, since PR was abandoned. Feel free to reopen it
