### ISSUE TITLE
.git/hooks//pre-commit: line 2: pre-commit: command not found

### ISSUE THREAD

**Issue by gkiely** [toplenboren/simple-git-hooks#78]
Not sure why, but I started getting this error.
Tried re-installing and following the readme but still seeing it. I can confirm the binary is present. Let me know how I can help.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1948935/182283680-e0d16914-1c6a-49f9-881b-06d5098e5aba.png">

Repo: https://github.com/gkiely/vite-react-starter

**Comment by toplenboren** [comment]
could you please share your `.git/pre-commit.sh` file? It seems like the wrong command is executing

correct command should be `yarn pre-commit` or `npm run-script pre-commit`

**Comment by gkiely** [comment]
That was the fix, my apologies I didn't think to inspect it, I thought it was a binary.
Previous: `pre-commit`
Working: `npm run pre-commit`
