### ISSUE TITLE
Missing tag 2.8.1 here

### ISSUE THREAD

**Issue by sfe-efficy** [toplenboren/simple-git-hooks#84]
Hi,

In [npm](https://www.npmjs.com/package/simple-git-hooks?activeTab=versions) latest version is 2.8.1, but here it's missing the tag to define what is new.

I guess is related with last PR accepted:

https://github.com/toplenboren/simple-git-hooks/pull/81

**Comment by toplenboren** [comment]
Hi, thanks for mentioning it. Sorry for the delayed response >_<

https://github.com/toplenboren/simple-git-hooks/releases/tag/2.8.1
