### ISSUE TITLE
Skip hooks installation when env variable is set

### ISSUE THREAD

**Issue by pantosha** [toplenboren/simple-git-hooks#87]
It's useful to skip git hooks installation when environment variable is set, e.g. SIMPLE_GIT_HOOKS=0

Similar functionality in husky: https://typicode.github.io/husky/guide.html#bypass-hooks

**Comment by toplenboren** [comment]
Hi, yep, this would be a nice feature to implement. However, if im not mistaken, you can omit from using git hooks using `--no-verify option` when you run `git commit`

**Comment by 7rulnik** [comment]
Yeah, you can commit via CLI, but in GUI (like Fork) usually it's not really possible

**Comment by jochemkeller** [comment]
I think this issue can be closed once #96 is made available as a new NPM version 🙏

**Comment by toplenboren** [comment]
Should be live in `2.10.0`. Thanks @pantosha for the issue and big thanks to the @bhanuprasadcherukuvada for the PR #96 

https://www.npmjs.com/package/simple-git-hooks
