### ISSUE TITLE
 Presence of yarn.lock despite packageManager set to npm

### ISSUE THREAD

**Issue by bhanuprasadcherukuvada** [toplenboren/simple-git-hooks#94]
I was looking through the repository and noticed something I wanted to clarify. In the package.json, the packageManager is set to npm. However, there's a yarn.lock file present in the project.

Is the yarn.lock file committed by mistake? If the project is solely relying on npm, would it be appropriate to remove the yarn.lock file to avoid any potential package management conflicts or confusion for contributors?

I appreciate your guidance on this matter, and thank you for all the work you've put into this package!

**Comment by toplenboren** [comment]
Hi! 

Thanks for the issue :-) 

I believe this should not cause any harm, since npm install of this package do not contain any dependencies. 

You can check for yourself that [`package.json`](https://github.com/toplenboren/simple-git-hooks/blob/master/package.json) contains only `devDependencies`

**Comment by toplenboren** [comment]
If you are looking to edit this package, you can use both yarn and npm, this project is so small it shouldn't matter to you
