### ISSUE TITLE
[feat] Add a new option to skip enabling on CI

### ISSUE THREAD

**Issue by JounQin** [toplenboren/simple-git-hooks#99]
As title

**Comment by toplenboren** [comment]
Hi! I think this is going to be implemented once #96 make it to `npm`

**Comment by JounQin** [comment]
#96 is a bit different for skipping on committing, while this issue aims skipping installation at the beginning.

I'd like to work on a PR soon.

**Comment by JounQin** [comment]
@toplenboren I'd like to reuse `SKIP_SIMPLE_GIT_HOOKS` environment variable, how do you think?

**Comment by peschee** [comment]
@JounQin Many CI environments normally set the `CI` variable by default (https://docs.travis-ci.com/user/environment-variables/#default-environment-variables, https://docs.travis-ci.com/user/environment-variables/#default-environment-variables, https://docs.github.com/en/actions/learn-github-actions/variables), so it would be best to also support this by default.

**Comment by JounQin** [comment]
@peschee I think that would be a BREAKING CHANGE?

**Comment by peschee** [comment]
Yes, probably. But are there instances where you'd want the hooks to be installed in a CI environment?

**Comment by peschee** [comment]
Yes, I understand. Breaking changes can happen though, so I'd be inclined to still vote for handling `CI` env vars, since this is what many other tools do.

**Comment by JounQin** [comment]
I'm fine with BREAKING CHANGE or major version personally, let's wait for @toplenboren to confirm.

**Comment by toplenboren** [comment]
Why do we need any git hooks to be set in `CI` ?

Maybe we can just add the guard to `postinstall` script, so that it does not install git hooks if it is executed inside `CI` environment

**Comment by peschee** [comment]
Husky uses a custom env var for this: https://typicode.github.io/husky/how-to.html#ci-server-and-docker

Maybe it is easier to off-load the responsibility of skipping to the user all together. Using something like [is-ci](https://github.com/watson/is-ci) is pretty straightforward…

**Comment by JounQin** [comment]
> Why do we need any git hooks to be set in `CI`?

Checking commit message on CI for example.

**Comment by toplenboren** [comment]
By the way, what is your usecase @JounQin?

**Comment by JounQin** [comment]
@toplenboren 

In my company, we have components which checks previous commit message on CI.

While in some other components, we don't want to enable git hooks because we could commit automatically with other tools.

**Comment by toplenboren** [comment]
> @toplenboren
> 
> In my company, we have components which checks previous commit message on CI.
> 
> While in some other components, we don't want to enable git hooks because we could commit automatically with other tools.

Thank you for clarification!

Why simply using `SKIP_SIMPLE_GIT_HOOKS` would not work? Hooks will be installed, but not executed

**Comment by JounQin** [comment]
@toplenboren 

That's the point, we don't want the hooks to be installed and logs `echo "[INFO] SKIP_SIMPLE_GIT_HOOKS is set to 1, skipping hook."` on every commit.

**Comment by toplenboren** [comment]
Let's add `SKIP_INSTALL_SIMPLE_GIT_HOOKS` env variable support, and add CI variable support

1. Case: SKIP_INSTALL_SIMPLE_GIT_HOOKS is not set
- If not set and if in CI -> do NOT install hooks
- If not set and not in CI -> install hooks

2. SKIP_INSTALL_SIMPLE_GIT_HOOKS=1
- Install hooks

3. SKIP_INSTALL_SIMPLE_GIT_HOOKS=0
- do NOT install hooks

This way we will:
1. have the env var namings consistent: `SKIP_*`
2. be able to address each case
3. not need to do a major release

What do you think, @JounQin. Will this cover your usecases?

**Comment by JounQin** [comment]
Do you want to add a dependency like `is-ci`? I think it's out scope of this tool, the user should easily add an environment variable for their needs.

**Comment by peschee** [comment]
It seems we're talking about two different things…

The way I meant it is what is in the husky docs. They DO NOT include the `is-ci` package in husky, but rather rely on the user controlling whether they call `husky install` or not (using `is-ci` or any whatever other method).

My point was: this library is probably better of not including an additional dependency.

**Comment by JounQin** [comment]
Oh, yes, I also think we should not check about CI on this lib's side. Do you have the consensus here?

**Comment by toplenboren** [comment]
I honestly really like this idea:

> @JounQin Many CI environments normally set the `CI` variable by default (https://docs.travis-ci.com/user/environment-variables/#default-environment-variables, https://docs.travis-ci.com/user/environment-variables/#default-environment-variables, https://docs.github.com/en/actions/learn-github-actions/variables), so it would be best to also support this by default.

Let's just check `CI` variable

**Comment by JounQin** [comment]
> Case: SKIP_INSTALL_SIMPLE_GIT_HOOKS is not set
> - If not set and if in CI -> do NOT install hooks
> - If not set and not in CI -> install hooks

> not need to do a major release

Isn't it a BREAKING CHANGE for not installing on CI by default?

**Comment by toplenboren** [comment]
> > Let's just check CI variable and add INSTALL_SIMPLE_GITH_HOOKS to explicitly configure this package for narrow usecases
> 
> OK, I'm personally fine with this strategy.
> 
> > Case: SKIP_INSTALL_SIMPLE_GIT_HOOKS is not set
> > 
> > * If not set and if in CI -> do NOT install hooks
> > * If not set and not in CI -> install hooks
> 
> > not need to do a major release
> 
> Isn't it a BREAKING CHANGE for not installing on CI by default?

Well.. technically yes.. :( I think we can do a major release, no problem

We can also split: first add the ability to configure INSTALL_SIMPLE_GIT_HOOKS and then add CI processing and update major

**Comment by JounQin** [comment]
I'll work on it soon.
